"""
MET aproximados para fuerza y cardio (referencia tipo Compendium).

Calorías (ACSM / compendio habitual):
  kcal = (MET × 3.5 × peso_kg / 200) × minutos
Equivalente: kcal/min = (MET × 3.5 × peso_kg) / 200
"""

from typing import Dict

METS_GYM: Dict[str, float] = {
    # Pesas / Fuerza
    "pesas": 5.0,
    "pesa": 5.0,
    "peso libre": 5.0,
    "mancuernas": 4.5,
    "barra": 5.0,
    "sentadilla": 5.5,
    "squat": 5.5,
    "press banca": 5.0,
    "press de banca": 5.0,
    "bench press": 5.0,
    "deadlift": 6.0,
    "peso muerto": 6.0,
    "dominadas": 5.0,
    "pull up": 5.0,
    "jalón": 4.5,
    "remo": 5.0,
    "curl biceps": 4.0,
    "curl de biceps": 4.0,
    "triceps": 4.0,
    "hombros": 4.5,
    "press militar": 4.5,
    "leg press": 5.0,
    "prensa": 5.0,
    # Máquinas / pierna (claves largas primero para matching por subcadena)
    "extensiones de piernas": 4.0,
    "extensiones de pierna": 4.0,
    "extensión de piernas": 4.0,
    "extensión de pierna": 4.0,
    "extension de piernas": 4.0,
    "extension de pierna": 4.0,
    "elevaciones de piernas": 3.8,
    "elevaciones de pierna": 3.8,
    "elevación de piernas": 3.8,
    "elevación de pierna": 3.8,
    "elevacion de piernas": 3.8,
    "elevacion de pierna": 3.8,
    "elevación lateral": 3.5,
    "patada de glúteo": 4.0,
    "patada trasera": 4.0,
    "prensa de pierna": 5.0,
    "prensa de piernas": 5.0,
    "curl femoral": 4.5,
    "curl de femoral": 4.5,
    "extensión": 4.0,
    "extensiones": 4.0,
    "elevaciones": 3.8,
    "femoral": 4.5,
    "hip thrust": 4.5,
    "glúteos": 4.0,
    "glúte": 4.0,
    # Cardio de Gym
    "caminadora": 4.5,
    "trotadora": 7.0,
    "trotar caminadora": 7.0,
    "elíptica": 5.0,
    "bicicleta estática": 6.0,
    "spinning": 8.5,
    "remo máquina": 7.0,
    "rowing": 7.0,
    "escaladora": 8.0,
    "stepper": 6.0,
    # Cardio General (gym o fuera)
    "cardio": 6.0,
    "hiit": 10.0,
    "circuito": 7.0,
    "funcional": 6.5,
    "trotar": 8.0,
    "correr": 10.0,
    "saltar soga": 9.0,
    "cuerda": 9.0,
    # Core / Abs
    "abdominales": 3.8,
    "abs": 3.8,
    "plancha": 4.0,
    "crunch": 3.8,
    "core": 4.0,
    "flexiones": 4.0,
    "push up": 4.0,
    "fondos en paralelas": 5.0,
    "fondos en banco": 4.5,
    "fondos": 5.0,
    "paralelas": 5.0,
    "zancadas": 4.5,
    "lunges": 4.5,
    "aperturas": 4.0,
    "burpees": 10.0,
    # Rutinas completas (aproximado)
    "rutina de pecho": 5.0,
    "rutina de espalda": 5.0,
    "rutina de pierna": 5.5,
    "rutina de hombros": 4.5,
    "rutina de brazo": 4.0,
    "rutina de brazos": 4.0,
    "día de pierna": 5.5,
    "día de pecho": 5.0,
    "día de espalda": 5.0,
    "entrené": 5.0,
    "entrene": 5.0,
    "entrenamiento": 5.0,
    "gym": 5.0,
    # Yoga / Pilates / Otros
    "yoga": 2.5,
    "pilates": 3.5,
    "stretching": 2.5,
    "estiramientos": 2.5,
    "natación": 7.0,
    "nadar": 7.0,
    "boxeo": 9.0,
    "zumba": 6.5,
    # Inglés (algunas sugerencias de la IA o usuarios bilingües)
    "leg extension": 4.0,
    "leg raise": 3.8,
    "leg curl": 4.5,
    "calf raise": 3.5,
    "lateral raise": 3.5,
}
